image:
  file: .gitpod.Dockerfile
vscode: 
  extensions:
    - ms-python.isort
    - ms-python.python
    - charliermarsh.ruff
    
tasks:
  - name: OpenAI Chat Interface
    command: pip install -r requirements.txt && python3 interactive-playground.py
  - name: Temporal Dev Env
    command: python -m venv env && source env/bin/activate && pip install -r src/requirements.txt && cd src/
  - name: Temporal Dev Server
    command:  temporal server start-dev

ports:
  - port: 8233
    onOpen: open-preview
    name: Temporal Frontend