image: gitpod/workspace-python

tasks:
  # Install the dependencies specified in your requirements.txt file
  - init: echo "fastapi uvicorn python-dotenv python-social-auth boto3" > requirements.txt && pip install -r requirements.txt
  # Run the FastAPI application using uvicorn
  - command: uvicorn main:app --host 0.0.0.0 --port 8000

# Expose the FastAPI application port
ports:
  - port: 8000
    onOpen: open-preview
